### ISSUE TITLE
Celluloid::Logger breaks existing code

### ISSUE THREAD

**Issue by ioquatix** [celluloid/celluloid-io#107]
In classes which `include Celluloid::IO`, if you write `Logger.new` in that context, you won't get `::Logger` but `Celluloid::Logger` which can cause problems for existing code:

    NoMethodError: undefined method `new' for Celluloid::Logger:Module

Let me know if you'd like me to write a failing test case.

**Comment by digitalextremist** [comment]
Definitely being handled at celluloid/celluloid#420
