### ISSUE TITLE
Errno::EMFILE: Too many open files - pipe

### ISSUE THREAD

**Issue by blanchma** [celluloid/celluloid-io#123]
Case:
Running several times a class which do http requests:

class SmsService
  include Celluloid::IO

 def initialize
     ...
  end 

  def deliver
      response = HaHelper::HTTP.get(url, ssl_socket_class: Celluloid::IO::SSLSocket).to_s
  end
end

Environment:
rvm use 1.9.3-p484

    celluloid (0.16.0)
    celluloid-io (0.16.1)
    http (0.6.2)

Stacktrace:

Celluloid::PoolManager: async call `perform` aborted!
Errno::EMFILE: Too many open files - pipe
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-io-0.16.1/lib/celluloid/io/reactor.rb:16:in `new'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-io-0.16.1/lib/celluloid/io/reactor.rb:16:in `initialize'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid/evented_mailbox.rb:9:in `new'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid/evented_mailbox.rb:9:in `initialize'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-io-0.16.1/lib/celluloid/io/mailbox.rb:6:in `initialize'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid/actor.rb:105:in `new'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid/actor.rb:105:in `initialize'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid/cell.rb:21:in `new'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid/cell.rb:21:in `initialize'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid.rb:168:in `new'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/celluloid-0.16.0/lib/celluloid.rb:168:in `new'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/http-0.6.2/lib/http/chainable.rb:140:in `branch'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/http-0.6.2/lib/http/chainable.rb:52:in `request'
	/Users/blanchma/.rvm/gems/ruby-1.9.3-p484@applicationservice/gems/http-0.6.2/lib/http/chainable.rb:12:in `get'
	/Users/blanchma/workspace/applicationservice/app/services/sms_service.rb:49:in `deliver'

**Comment by digitalextremist** [comment]
As per responses, this is a common issue on an Operating System level -- not `Celluloid::IO`. @ioquatix shows you the solution using `ulimit` under Mac OS X.
