### ISSUE TITLE
Prerelease versioning scheme violates semantic versioning and breaks gem dependencies

### ISSUE THREAD

**Issue by matt-altiscale** [celluloid/celluloid-io#144]

**Comment by matt-altiscale** [comment]
Gem::DependencyError: Unable to resolve dependencies: berkshelf-api requires celluloid (~> 0.16.0.pre); reel requires celluloid (>= 0.15.1); ridley requires celluloid (~> 0.16.0); celluloid-io requires celluloid (>= 0.17.0.pre12)

**Comment by matt-altiscale** [comment]
Prerelease identifiers should be separated from the main version by a hyphen:  0.17.0-pre12.

**Comment by tarcieri** [comment]
According to what? It certainly isn't documented that way at RubyGems.org:

http://guides.rubygems.org/patterns/#prerelease-gems

Furthermore, semantic versioning doesn't apply to 0.x releases.

**Comment by tarcieri** [comment]
I think your problem is actually the way you're locking to versions. Don't lock to `~> 0.16.0.pre`

**Comment by digitalextremist** [comment]
We are at `0.17.1` in this gem, and `0.17.1.2` in the other. No `.pre` releases are currently in the wild, and we are well on our way to `1.*` across all libraries.

**Comment by ioquatix** [comment]
Hmm. Yes, I tend to use versions like "1.0.0-rc11" for release candidates.
