### ISSUE TITLE
Release a version compatible with «require 'celluloid/current'» with Celluloid v0.17.x.

### ISSUE THREAD

**Issue by clonezone** [celluloid/celluloid-io#149]
Celluloid-IO v0.16.2 dies by trying to use `Celluloid::EventedMailbox` for me if I replace `require 'celluloid'` with `require 'celluloid/current'`.

**Comment by digitalextremist** [comment]
I will release the `0.17.0` version of this gem today, with more `deprecate.rb` mappings

**Comment by digitalextremist** [comment]
`0.17.0` is on Rubygems now.

**Comment by clonezone** [comment]
Sorry for the late response, but a cold has been kicking my butt for the past several days.

This now works. I've still got issues, but they can be discussed on the list.

**Comment by digitalextremist** [comment]
Right on. Get well //
