### ISSUE TITLE
v0.17.0's dependency upon timers conflicts with celluloid v0.17.1.2's dependency on it.

### ISSUE THREAD

**Issue by clonezone** [celluloid/celluloid-io#152]
`celluloid-io` v0.17.0 has a "~> 4.0.0" requirement on `timers` which conflicts with `celluloid` v0.17.1.2's ">= 4.1.1" requirement on `timers`.

**Comment by digitalextremist** [comment]
I will recut `Celluloid::IO` -- which I believe is the only one I haven't recut with the new dependencies.

**Comment by digitalextremist** [comment]
Resolved
