### ISSUE TITLE
Does it work with ruby 2.1, 2.2, 2.3?

### ISSUE THREAD

**Issue by jan** [celluloid/celluloid-io#177]
> Celluloid::IO works on Ruby 1.9.3, 2.0.0, JRuby 1.6+, and Rubinius 2.0.

All support for ruby 2.0 has ended. Current version of Ruby is 2.3.1, so it's probably time to update this statement?

**Comment by digitalextremist** [comment]
Thanks @jan, made the change. In the future, don't be shy about proposing changes you see needed... go ahead and skip right to posting a Pull Request with your idea of how it ought to be.
