### ISSUE TITLE
Review of net-http-celluloid-io gem modifications

### ISSUE THREAD

**Issue by kamk** [celluloid/celluloid-io#183]
I have forked [net-http-celluloid-io](https://github.com/kamk/net-http-celluloid-io) gem. I would be appreciate if anyone could review the code of current version. Tests don't seem to work as original gem is based on older version of Celluloid::IO

**Comment by tarcieri** [comment]
I'm afraid I don't know anything about this library and don't have time to review it.

This is an issue tracker for bugs in Celluloid. If you would like to find people who are interested in reviewing this, I would suggest posting to the Celluloid Google Group:

https://groups.google.com/forum/#!forum/celluloid-ruby

**Comment by ioquatix** [comment]
Interesting fork. I don't have time to review it, but I can point you towards a more recent attempt for concurrent Ruby IO: https://github.com/socketry/async-io

There is some existing integration with `Net::HTTP` in here https://github.com/socketry/async-io/blob/master/spec/async/io/wrap/tcp_spec.rb
