### ISSUE TITLE
Rubinius, pools and HTTP causes strange behaviour

### ISSUE THREAD

**Issue by myitcv** [celluloid/celluloid-io#95]
Hi - first, thanks for all the work on `celluloid`. Looks great!

We're hitting two problems when using `celluloid`, `celluloid-io` and `http` atop Rubinius. At a high level:

1. Use of a pool with `celluloid-io` doesn't work as expected (although I will fully accept our expectations might be the thing that needs adjusting) - IO appears to become blocking
2. A simple app crashes within the `http` gem (similar issue I believe to #84) due to a `ArgumentError: Data object has already been freed` error

The code we are using can be found in [this gist](https://gist.github.com/myitcv/22d3de3161e925eb72be). The steps to repro are as follows:

* [`server.rb`](https://gist.github.com/myitcv/22d3de3161e925eb72be#file-server-rb) was run using MRI `2.0.0p353` using Puma
* [`repro.rb`](https://gist.github.com/myitcv/22d3de3161e925eb72be#file-repro-rb) was run using Rubinius (see system details below)
* [`Gemfile`](https://gist.github.com/myitcv/22d3de3161e925eb72be#file-gemfile) for `repro.rb`

There are two output files that correspond to the following variations of [this line of code in `repro.rb`](https://gist.github.com/myitcv/22d3de3161e925eb72be#file-repro-rb-L17):

* Scenario 1: **[`output_1.txt`](https://gist.github.com/myitcv/22d3de3161e925eb72be#file-output_1-txt)** - `fetcher = HttpFetcher.pool`
* Scenario 2: **[`output_2.txt`](https://gist.github.com/myitcv/22d3de3161e925eb72be#file-output_2-txt)** - `fetcher = HttpFetcher.new`

`server.rb` contains a random sleep, hence in both cases our expectation was that all requests would be fired off immediately (puma runs with 16 threads by default and so all 10 can be handled simultaneously) and then return in a random order (which we see from the [output of `server.rb`](https://gist.github.com/myitcv/22d3de3161e925eb72be#file-output_server-txt))

However [what we see from scenario 1](https://gist.github.com/myitcv/22d3de3161e925eb72be#file-output_1-txt-L1-L6) is that only 4 requests are fired off initially, i.e. they appear to block, despite the actor including `Celluloid::IO`. Additionally this crashes with the ['ArgumentError: Data object has already been freed'](https://gist.github.com/myitcv/22d3de3161e925eb72be#file-output_1-txt-L10) error.

Scenario 2 behaves as expected from a threading perspective, but [suffers a similar crash to scenario 1](https://gist.github.com/myitcv/22d3de3161e925eb72be#file-ouput_2-txt-L25).

Any help much appreciated.

 ```bash
$ uname -a
Linux myitcv-virtual-machine 3.11.0-15-generic #23-Ubuntu SMP Mon Dec 9 18:17:04 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
$ ruby -v
rubinius 2.2.3 (2.1.0 4792e746 2013-12-29 JI) [x86_64-linux-gnu]
$ ruby -r 'celluloid' -e 'puts Celluloid.cores'
4
```

Versions of gems etc per [`Gemfile.lock`](https://gist.github.com/myitcv/22d3de3161e925eb72be#file-gemfile-lock)

**Comment by digitalextremist** [comment]
@myitcv still open?

**Comment by myitcv** [comment]
Haven't looked at this in ages so you can probably close. Thanks
