### ISSUE TITLE
Celluloid::IO 0.15.0 incompatible with Net::SSH 2.8.x

### ISSUE THREAD

**Issue by TiagoCardoso1983** [celluloid/celluloid-io#99]
Just tried using Net::SSH connection with Celluloid::IO::TCPSocket using the latest versions and it failed. It seems that it passes an hash to the third argument of the TCPSocket constructor, which is expected to be a String by Celluloid::IO. 

I downgraded to version 2.0.14 of Net::SSH and everything worked.

**Comment by TiagoCardoso1983** [comment]
I guess this has to do with net-ssh and how it handles proxies, celluloid doesn't have anything to do wiht it.

**Comment by TiagoCardoso1983** [comment]
The "issue" has been clarified. See https://github.com/net-ssh/net-ssh/issues/220#issuecomment-70456647

I think this is more a question of misleading documentation, see https://github.com/celluloid/celluloid-io/wiki/Libraries-that-support-Celluloid%3A%3AIO for net-ssh compatibility. You cannot unfortunately just override the proxy class, but provide a "proxified" way to initialize the socket. 

Would like to see the proxy feature also documented on the net-ssh side, though.

**Comment by digitalextremist** [comment]
@TiagoCardoso1983, I linked your comment to the Wiki. Feel free to expound and I will port your caveats to the Wiki.
